const { deriveCycleMonth } = require('./balance');

// UX quirk (T3): legacy cycle-only payments (empty paid_purchases) don't tag
// specific purchases, so the purchases they covered stay in the picker's
// "unpaid" list forever. This is the audit-trail cost of not backfilling old
// rows on read. Users migrating from the pre-extension era will see legacy
// purchases as unpaid until they either (a) tag them via a new payment, or
// (b) accept that the audit trail is what it is.

// synthesizeTxId assigns a deterministic id to a legacy row that lacks one so
// that hydratePurchases and listUnpaidPurchases can index by it. The `ps_`
// prefix (synthesized) is intentionally distinct from `p_` (generated by
// sheets.addTransaction) so grep and logs can tell reconstructed ids from
// assigned ones at a glance. `rowIndex` is a tiebreak for the pathological
// case of two rows sharing a timestamp — pass the array index of the row
// within its source list.
function synthesizeTxId(row, rowIndex) {
  if (row && row.tx_id) return row.tx_id;
  const parsed = Date.parse((row && row.timestamp) || '');
  const base = Number.isFinite(parsed) ? parsed : 0;
  if (rowIndex !== undefined) return `ps_${base}_${rowIndex}`;
  return `ps_${base}`;
}

// Batch resolution uses the plain (no-suffix) synthesized id. Timestamp
// collisions among legacy rows would produce the same id — extremely rare
// with ms-precision ISO timestamps written by the bot, and one purchase would
// "win" the id for payment-tagging purposes. Callers that need collision-safe
// disambiguation should pass rowIndex explicitly to synthesizeTxId.
function resolveTxId(row) {
  return row.tx_id || synthesizeTxId(row);
}

// hydratePurchases builds a Map<tx_id, purchase> from the transactions list
// (purchase rows only) and returns purchases in the order of txIds. Unknown
// ids are silently skipped — corrections happen via new rows, not mutation, so
// a payment row referencing an id that no longer exists is treated as if the
// tag were absent rather than raising.
function hydratePurchases(txIds, transactions) {
  const index = new Map();
  for (const tx of transactions) {
    if (tx.type !== 'purchase') continue;
    const id = resolveTxId(tx);
    if (!index.has(id)) index.set(id, { ...tx, tx_id: id });
  }
  const out = [];
  for (const id of txIds) {
    const p = index.get(id);
    if (p) out.push(p);
  }
  return out;
}

// listUnpaidPurchases returns purchase rows for `cardName` (case-insensitive)
// that do NOT appear in any purchase-tagged payment's paid_purchases. Legacy
// cycle-only payments (empty paid_purchases) contribute nothing to the paid
// set — see the UX quirk comment above.
//
// Every returned row has its tx_id resolved (synthesized for legacy rows).
// Cross-card contamination is prevented by filtering payments to the same
// card before building the paid set — otherwise a same-timestamp legacy id
// on another card could mask this card's purchases.
function listUnpaidPurchases(cardName, transactions) {
  const target = String(cardName).toLowerCase();
  const paid = new Set();
  for (const tx of transactions) {
    if (tx.type !== 'payment') continue;
    if (String(tx.card_name).toLowerCase() !== target) continue;
    const tagged = Array.isArray(tx.paid_purchases) ? tx.paid_purchases : [];
    for (const id of tagged) paid.add(id);
  }
  const out = [];
  for (const tx of transactions) {
    if (tx.type !== 'purchase') continue;
    if (String(tx.card_name).toLowerCase() !== target) continue;
    const id = resolveTxId(tx);
    if (paid.has(id)) continue;
    out.push({ ...tx, tx_id: id });
  }
  return out;
}

// inferCycleFromPurchases groups annotated purchases by their derived cycle
// month (using deriveCycleMonth from balance.js so the statement_day boundary
// stays consistent with statement-close logic). Callers get one of three
// shapes so the picker can render the right UX: single-cycle → seed the
// payment row; multi-cycle → set statement_cycle='' + surface a warning;
// empty → nothing selected (picker should have blocked Done earlier).
function inferCycleFromPurchases(purchases, statementDay) {
  if (!purchases || purchases.length === 0) return { empty: true };
  const cycles = new Set();
  for (const p of purchases) {
    const [y, m, d] = String(p.tx_date).split('-').map(Number);
    if (!y || !m || !d) continue;
    // Construct a UTC date for the tx_date so deriveCycleMonth's UTC math lines up.
    const asDate = new Date(Date.UTC(y, m - 1, d));
    cycles.add(deriveCycleMonth(statementDay, asDate));
  }
  const arr = [...cycles];
  if (arr.length === 1) return { cycle_month: arr[0] };
  return { multi: true, cycles: arr };
}

module.exports = {
  synthesizeTxId,
  hydratePurchases,
  listUnpaidPurchases,
  inferCycleFromPurchases,
};
